"""2 миграция

Revision ID: 4b6e4634d4fe
Revises: b5f7708b2b3d
Create Date: 2025-05-02 17:14:56.166959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6e4634d4fe'
down_revision = 'b5f7708b2b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
